#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# gen-conftest-stubs.sh — build the conftest data-import stub object.
#
# The NanOS libc declares its DATA exports (stdin/stdout/stderr/errno/environ/optarg/
# locale + iconv tables ...) as plain `extern` symbols. They are left UNDEFINED at link
# time and bound by mknx's MinGW-style auto-import against libc.ndl (the static libc.a
# carries an `__imp_<name>` IAT slot for each). The final program link uses the spec's
# --unresolved-symbols=ignore-all so those references survive for mknx to fix up.
#
# autoconf's link probes (AC_CHECK_FUNC) must instead be STRICT, or every function looks
# present (see conftest-strict-wrapper.sh, which appends --unresolved-symbols=report-all
# to conftest links). But report-all is TOO strict: a probe like gnulib's __fpending test
#   size_t __fpending(FILE*); return ! __fpending(stdin);
# references the libc DATA symbol `stdin`, which is never defined at link time, so the
# probe fails to link and the (present) function is wrongly reported absent.
#
# Fix: this object WEAKLY defines exactly the data-only import names — those that have an
# `__imp_<name>` slot in libc.a but NO strong definition there (i.e. the pure-data exports,
# not functions, which resolve from libc.a normally). The wrapper adds it to conftest links.
# Result: a conftest resolves iff libc actually provides the symbol — functions strictly
# from libc.a, data via these weak placeholders — so detection is faithful. The set is
# derived mechanically from libc.a, so it stays correct as the libc evolves.
#
# Usage: gen-conftest-stubs.sh <sysroot-lib-dir>   (dir holding libc.a; output goes there)
set -e
LIBDIR="$1"
[ -n "$LIBDIR" ] && [ -f "$LIBDIR/libc.a" ] || { echo "usage: gen-conftest-stubs.sh <dir-with-libc.a>"; exit 1; }
NM=${NM:-i686-nanos-nm}
CC=${CONFTEST_STUB_CC:-i686-nanos-gcc.real}
command -v "$CC" >/dev/null 2>&1 || CC=i686-nanos-gcc

LIBC="$LIBDIR/libc.a"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# A = every importable name (strip the __imp_ prefix); B = every strong definition in libc.a.
# A - B = the pure-data exports that have no strong definition (stdin, errno, environ, ...).
"$NM" "$LIBC" 2>/dev/null | grep -oE '__imp_[A-Za-z0-9_]+' | sed 's/^__imp_//' | sort -u > "$tmp/A"
"$NM" "$LIBC" 2>/dev/null | awk '/^[0-9a-fA-F]+ [TDBRGSWVtdbrgsw] / {print $3}' | grep -v '^__imp_' | sort -u > "$tmp/B"
comm -23 "$tmp/A" "$tmp/B" > "$tmp/dataonly"

{
	echo '/* auto-generated by gen-conftest-stubs.sh — weak placeholders for libc.ndl DATA'
	echo '   imports, so autoconf conftest links resolve them without masking absent functions.'
	echo '   conftest is never executed, so the value (0) is irrelevant; only the symbol matters. */'
	while read -r n; do
		printf '.weak %s\n.set %s, 0\n' "$n" "$n"
	done < "$tmp/dataonly"
} > "$tmp/conftest-data-stubs.s"

"$CC" -c "$tmp/conftest-data-stubs.s" -o "$LIBDIR/conftest-data-stubs.o"
echo "  built $LIBDIR/conftest-data-stubs.o ($(wc -l < "$tmp/dataonly") data imports)"
